### ISSUE TITLE
CPU instruction identification issue?

### ISSUE THREAD

**Issue by hongshui3000** [dan-c-underwood/vscode-arm#31]
![image](https://user-images.githubusercontent.com/25566498/154459322-d1b7b341-d0f8-499f-b494-a844e481575f.png)
![image](https://user-images.githubusercontent.com/25566498/154460072-c565bba6-806a-4cb4-8a25-8f178e81a77d.png)

**Comment by dan-c-underwood** [comment]
Thanks! The instruction was missing. Now added in v.1.7.4.

**Comment by hongshui3000** [comment]
It still doesn't seem right? colour 
![1645759390(1)](https://user-images.githubusercontent.com/25566498/155647817-760311d8-4278-4352-bcd7-03356b8e065f.jpg)

**Comment by dan-c-underwood** [comment]
Sorry for the delay in my reply. That colour difference was semi-intentional, in that it will depend on the colour theme used within the editor. As with some of the instruction types, I put the CPU-control instructions under a different keyword than the memory-based or arithmetic-based instructions are under. Happy to move them under the same keyword - but I find having variation in highlighting can aid visual recognition.

Feedback welcome!
